### PR TITLE
SFTP (FTP over SSH) provisioning

### PR DESCRIPTION
**Pull request by dschealler**
SFTP is not supported by vsftpd.sh. The ssh.sh script fills that particular gap.

Also includes a minor update to vsftpd.sh.

### CODE REVIEW

**Review by cdaf — APPROVED** [review]
Can you please send me a sample vagrant file to test?

**Comment by dschealler** [comment]
Here you go.

[Vagrantfile.zip](https://github.com/cdaf/linux/files/505537/Vagrantfile.zip)

**Comment by cdaf** [comment]
Please remove custom componens

PS F:\linux> vagrant up
Bringing machine 'sftp' up with 'virtualbox' provider...
Bringing machine 'sftpcr' up with 'virtualbox' provider...
There are errors in the configuration of this machine. Please fix
the following errors and try again:

shell provisioner:
- `path` for shell provisioner does not exist on the host system: F:/WOLS/linux/automation/solution/customLocal/qafolders.sh

**Comment by dschealler** [comment]
[Vagrantfile.zip](https://github.com/cdaf/linux/files/507444/Vagrantfile.zip)

**Pull request merged**
